# Generated by Django 3.0.3 on 2021-05-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(default='IEDC-JECC', max_length=100)),
                ('photo', models.ImageField(upload_to='images/events')),
                ('photo_Desc', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='photos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.all_photos'),
        ),
    ]
