# Generated by Django 3.0.3 on 2021-05-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210510_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='photos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.photos'),
        ),
    ]
