# Generated by Django 3.0.3 on 2021-05-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210510_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
        migrations.AlterField(
            model_name='all_photos',
            name='photo_name',
            field=models.CharField(max_length=100),
        ),
    ]
