# Generated by Django 3.0.3 on 2021-05-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210510_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Photo_1',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Photo_2',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Photo_3',
        ),
        migrations.AddField(
            model_name='events',
            name='Event_Home_visible',
            field=models.BooleanField(default=False),
        ),
    ]
